# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: phytec
      url-base: https://github.com/phytec

  projects:
    - name: zephyr
      remote: phytec
      repo-path: zephyr-phytec
#      revision: WIP/jma@phytec.com/v4.4.0-phynext
#      revision: f7a4352fb43ff289bfa38ebb600b74e973f2008c
#      revision: 28ae7e8bccbd593ab75890fc86f1e2a8f04f60ed
#      revision: 9edd557451924c919bfeecbf4f836f475d412ac9
#      revision: d2898d3bd5d0a6bf1ab1d772fb21567e6d77775c
#      revision: 9da5c076159ce242ced0fa97fcd8088d4bc6dfcb
#      revision: 4626c0eb2a7cd94ad25ae76d4ddd25d652236e19
#      revision: 68ad2ab5edc3d23be9d2d4614dd73f19c17cffeb
#      revision: d5c2e71fa6fc479269668bc99e3ed9bb6112257d
# OK      revision: 68c9caf740277d08aae895246679c3f2cd1a76e2
# OK      revision: c2d0717c46977a0bb628bf8d134008c29f07889e
      revision: b54e0ba58fde513965d077f99c9f22125fe19d68
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - cmsis_6
          - hal_nxp    # required by NXP boards
          - lvgl
          - fatfs
