# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: phytec
      url-base: https://github.com/phytec

  projects:
    - name: zephyr
      remote: phytec
      repo-path: zephyr-phytec
      revision: v4.0.0-phy1
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nxp    # required by NXP boards
