# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: jma-phytec
      url-base: https://github.com/jma-phytec

  projects:
    - name: zephyr
      remote: jma-phytec
      repo-path: zephyr-phytec-dev
      revision: WIP/jma@phytec.com/phyboard_atlas_dev
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nxp    # required by NXP boards
          - lvgl
          - fatfs
